step-runner-config:
    tag-source:
        - implementer: Git
          config:
            git-password: ENC[AES256_GCM,data:nx6l8cW3rb+RsEfdyCEdJBq2LL0=,iv:f/yxNhTAfEyl/X3xpI89dYZGSgz6t/Y3T1GfLja+8MU=,tag:EZIKPFjtHd9ogrwBg+LEWg==,type:str]
    deploy:
        - implementer: ArgoCD
          config:
            git-password: ENC[AES256_GCM,data:eBafEITgyzqmJ4STfX0JEBzvP4M=,iv:+TIS1aZ7cloCSEqOYp/KAs/NGnRfKF0+bnP+Z64ai7w=,tag:mB/NVqi3Iq9hRooB1eMVUQ==,type:str]
    uat:
        - implementer: NpmXunitIntegrationTest
          config:
            npm-envs:
                USER1_PASS: ENC[AES256_GCM,data:0b+x8BTdaZ9m2C1/Y2I6ng==,iv:tiL9nge5+INk6KtJIt3qjaYExCDxtc20tALF00tTgNQ=,tag:W9C+YD8GDmzC7crqJLQKBg==,type:str]
                USER2_PASS: ENC[AES256_GCM,data:inPyLaYCT2jCvj1j2ish1g==,iv:XzYDn/w0cP7pXcBOCzskHpQvXR8MM7/+KuKKcIDKsWY=,tag:pnJjhlzALcDC+pUM35gHEQ==,type:str]
                XAT_PASS: ENC[AES256_GCM,data:hMpXE8qBDj7pRTWk517VJw==,iv:2wM+3M+g+U0f0W5QzsyAZ3XTPHvCihobnxkiyvoJ28k=,tag:VDr8cUdGxuJBm99OYwQbnw==,type:str]
                XAT_PRIV_PASS: ENC[AES256_GCM,data:g6q+JX2NQJy+qJA4D67DmQ==,iv:IEqHgDsK8uQnJf8qA/YrdboBm/iQ7WxFOxC0izdUkvs=,tag:DWwtHY87taTlwKgY7DWPPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-01T18:04:31Z"
    mac: ENC[AES256_GCM,data:t5jU3H1hRtGmHXlCpJ4tZ5UMogKxsEPfThZ8/W2LYOurSjWEn3/UTW1Xo5gbkODonpzaZ0Lp/zoRe4fzJjutyR9yqRvt2cGeOmzRkw1YOE2ChdRJlFVIwGxBOfzB+E6PFv+c3HG6D2fw7hYgNTlF+d7ATsS4bkwzM8k88qjWxGo=,iv:vT8Ds9Tg+7XYLGo3d2HUd5+qZX8hFqV4a/ylONtNVdU=,tag:tuxMgf6MfvexpvstMjehwA==,type:str]
    pgp:
        - created_at: "2021-10-14T21:41:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ//T+Km6zMnVOTU+kNzOGlxYQ0h5mxNYgLLxpm6XdBvsrcU
            e3gzCqnbW56cwI2GJXIlbuDdRscjbYVKKYVmICoq9Vsq58XaeyrPYDP1q3d3RPcI
            RJZzgfVTcIc78BrK8U9xQ7ZN82Nnm9MW37UBjKyyfNiukqX1VYNyrhPgLrErGROm
            hvALUMTPbUi0Thhx98VBxxGvJhptBwZieF2KP3x5m6pdUFFf/8EqH2w23kax2wGM
            /v35FWeVBcKquBjSa1UsMOPfUZvRwBxxV0kfaiOoaUBYVh73KwUmCKHukMXU6aBL
            uNVkGBqhGrrXnhggcq3Wj/+KM7GZTW3AAlOza4gBO7BeK3zEKJDcu+0Rd7ifWwgG
            NUQWtVfrYtQsbOWXzRbbYwr1CEjyVJa0FvO3pueSJgZ48kzMIaU3fHg5+vwfrzoW
            QH5zTaivtCYeG52auP3dPVGVZa3718+h0gaMYVkEcbkDwGT6fsTYG8a87A1GdkzE
            sQwMU5CtwJyPYaBZB15V7LuZoT1yRD8VHmv5zX1Qrkjcp3qLw80642wVdQJ10lvR
            M0KN6O0Ox2jVJZ1EjkMSFnGkQDSF5wi8eRdcdxMhJRF7rQmFxbtUXO3MzN7hjoth
            xpE6mjUaWlraAjKKGKFTvgjlLK+wOl64oHXs9y0nkhD7jyJ5jUGAt0oxbxJDjlLS
            XAEkTLkBRvicm+Afw1A/lkRbsx6I2VDM7zhBH7DtM/fd+9sdBupYFI7r8m3FE94n
            DPq48TCqYiPxj6rm8bl9ETYkoMkRSldCLRU+0pL4mr3sDWHiGMve3ef3cIiO
            =evVs
            -----END PGP MESSAGE-----
          fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
        - created_at: "2021-10-14T21:44:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4cosCggMlEWAQ//XOt0uBjWrDNxDIOVDN5Vhr2aTEzCsF+ZnrmhUh+IKezN
            YvOnRxWCOrPGcGLNAnJxVLhq8+ylC74b0Z4vmO8e1hJi79FV5RfezS+QEeLM6/NC
            lqw0Quzge/D/q1zixkI532YGA+k6eCVRnoetXmnPQ4Z3KF30MeFqrab/ladaj4vf
            AIEMY6wg7EFTOn4kQDU2Aspze4jE/+DZXy/RSqFvAiXShbanG824CGg30nT8rv1v
            MwFdmysgFlLuoiVHxPt7NlgIZ4pYzjgP53bcXyzP5H3vbMVfY/2SUZ7nEBMMdpKJ
            ELDHX6Vc7DAmXFg8NPXDdBL/qvIokxKjAvkGM1i8Tyru6LpO6/S8zaBqbSe8dvEm
            Ql/ffwfljNbLNkSuRvxt8IxLu5swAwQVsfwG/f5qoZJuLx6g2E+xP5R/tPaHD9tD
            zZ5itkREktIuMm58jcXWrJwkd1i4AhDq25l1k9GxGziZKdAcPFtUZIbuE2lu13PG
            VexnolH+Xogm2UhIHkuewsCobZdEzbkPitJlCSky0S6YviXtc14q63n2y3uUIke3
            Fsm2xFI+H4tf9vx3N6MYKKaL1DrsrRYzphCGyV+nofHgF2EhqG9N+5KFPsFAf5m5
            gjrdrKJiCo8Kh2C3WlSHSmHshy2BxBWwFV/hR3iADFGpo/72xZZTPfFe6LYZgV3S
            XAFH6142jhQvpQ1kGZndIIXmkpa46641M4d9sN0u/0QsZMAKKyMwlRBDXJcpDzLA
            eKItbiPAw/uiVPwuFSgysk7gDysr4MAqyKkF7IBo7BiakzVV0PHc9wNRbV1L
            =zudM
            -----END PGP MESSAGE-----
          fp: 82CCC83BE58E7985C1FAD60399CA50E2B174AE29
        - created_at: "2021-10-14T21:44:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4VALzX5s2x4AQ/+KFqIaeonJnWUXbfJqJRiCvoQAoteOdTTXJ72XtpfJ5Lg
            Dcmc9VKFhxx4o9NYaQwXKtxXySfisj5gjZLeMrwtGkxJ97aCbuf5StmsDU76moOS
            gdY4k3H3x/oZIr5XWtEKnBup6z9P0lbsUtKTksYtA23FrvFmfgaRWbWbm3UEb4sm
            FzqU7kxJs0ifacx7T/1a1jKaYSSi84NU2fgoidzaiZWfFmTXqMzubFJ4QRfejzGq
            fFOnAlJHkJ8taDC3ZusTWThkvb1X4h2V4knlWpBIykog9+Kc8BV/FMjznuxhRTLH
            WWdiBYJvnYrUHDtd1Wn1tbqGRscJ7NkeepWhzJLCkMm8z1Qr+TLUEbyRuRIyYFy3
            z2NbSG3a9XlN3rwprOjpVPgfUvIcLfItpjP0YAAFZKgYOOlAkso8YlOAHW9G/4ok
            IyJv2NnhCCG9LBxG6uE0ZNBRDxW13/QXfGofSrFMxd4q0pyDcwaFiWZFt43KFvD7
            w4hpTY+YMam57iGOJejei2keNSRKZwYb2KYizzIs3WYB6l5gTZL98LBzjH0SBJx6
            2Uy3w5zSFIebA9GA+kGsqNeh6g2ngb3fkANaeBkop8U19cKM4+hji1r39BhRdWZY
            L3ZHV0LcyVkDHPSyBduFaZTs1HoHgexsoRwfgIPugmAocSO4X7pZ5W6zEuzUts/S
            XAF96YIXt1ic8z1o0PbOhf8yH/l31YV6F0ClgSpaUjazotWrcJpVJU5mG3jiv83/
            qsxoxVoWsyUAQ0PjRtNTTohO5R6gywxH3tWyRrK8lBxN5UyMFkrK3viqOuCL
            =y4dh
            -----END PGP MESSAGE-----
          fp: 8AE499DD092430C1E2DCE845E8F36B93FE52A6CF
        - created_at: "2021-10-14T21:44:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzlTOzb6XH5MAQ//X8+cLh/BSTo5WbHkGciKjw0rNpXUjsl43FM5nGUco4wm
            GTosUYOpv13k9TsDxNbj+GR1LRFry3FR1yY4B+wyxRDACxTMrW9pzV5yvx+JCztA
            5dGmp71oHyQh07Rvpel71Fwmt8nnM1qRp3/ch2yXdIEu+ad40GKIKkRuznQq3EoR
            qITtq11Ok5QMHH8zLp9ifNje0LyXRNuY9X1XgkKBMQRl00KH0a0Ne+AzuMS8F5pc
            N4ORY1NYaz0l1l+a2XY6nDhM5riASKv/o6MD/vs0twMt6BntEd9sxc1ShGlzFnq7
            ZNStq/SNBZu1HjTL6oB8CHv1eelN1ZiKshWqQ5L3ZywA41Yx95aW7aS6ABfadxH9
            t6SMKfvUzzCVlbTbCXtMuqz+U10LHTPtP/Xw02Jt8kyjxEM5GJnqsh0UUjQJNBjI
            k5d4aPx6Tw19WPNf4x7nYpi2JhqnDAZg8IJwTQqi/KTAvscT0k7xatrOHucRWgmd
            8v3Tx/CSMuYLj3NadMlQDW0TPb1Kn2n+aAN5hLSsSxSsHjDlk+w+4Taq5XmkziM8
            tdL06Lq1hQvIk/druMI2KEQF4y5Yzvt2LLATw4OmFGQ0pUYPUOgPT0luh6tlSVUH
            /nqiIWv1L/+5iRqw2fluZpMghPueinAA/2hjWuFBbHWMn2KjBEW2ByI4dw80IbrS
            XAHJelJw9S/74DDN+gE6M64srOeo+KyW2xb4a2bleBYd0NB4v3VwbjU0sidpbrg/
            4eAwg2ba9XQj8r1/YGYsYkdglio5bRZyaRIb5JJ4nzKHpSLEj5uTKVzZYGBD
            =h8Io
            -----END PGP MESSAGE-----
          fp: 2DBD7652E666814AD25711B1A6ADB6AA81DAB7B8
        - created_at: "2021-10-14T21:45:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxWhoUZAfyGVARAAhdtilzXm2kl5L5xK5MElplua5rFgctOrZy4fCIZXlTYA
            nAcOsGwK9a+QsZvMYu/S8igh5H5r3ClDyRGTAFVCt+qMHWfP4CDCuxyHm4BbPe10
            tQu5G4o3CF3ujUVq4mEUSoLw+6917iOE2e1TX7Lqhwqe77FThZc++LpBW0ZzD33a
            PuhAHy6zrn2GehS+W0Dv3b148GSkWKZJD63rGZrF5F27K0X8Gm94ToEfo3XGFLDq
            K3Qe74iUu9+vWDaRjIzccwBBL6g8kHhBTZMRKiJgMHq3Xwt+6oYAQyvnBUhOYXcm
            fCzZ8MQQesh7uOs+jZaP1yeRdZWN69exqMEIlQuZQwt+9S/cSrEK7Wg2UipGheNP
            al0QON1JmqSaNLcPNCKvJvXKz83R47fdFkLpOhnqBSciwxUJQfSTzDOxghYHFCAZ
            D8XthOyQQtID2GOXoAPAPqXTnQsNy6XQEia1+56j5X7Z/wA747fN1LSr1kmVXAj6
            wKs8+6Hjk1t5/uNprkgN3aYFnqC1xYb/o4otEWEp15wLD3fMZXTIup07T3nfd1iq
            3Gp8En2Tow4QnjrxbqE4tTVOFR7QbHAByUDCR5RjKpG4alJ7uYUsEsohu/LZWMjN
            3iWJBG5lkgLXO668xgUofQJHZ4wFPa2dKL2YhJDcFWklHInUocDOFiSIncVDpPnS
            XAHc1dJ95HflKR2SIY5HnKfIs82TvvaV/GU2CDJ7ufuj4KW5A3ZMDxCQ5MN4l3vy
            dnig2jc0rtKbs05MWEjbqB9b7+OKuaqfL2RdBxZk24A2BzA0TOI4oubUeQ9h
            =UMZ/
            -----END PGP MESSAGE-----
          fp: C0D9573DD441156D1A82B6FEED3EEE5904206977
        - created_at: "2021-10-20T19:22:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1j1M1wGETuWARAAst90neKVwi2aI0h/kQy+c+NI3DuTMPqI1Y02pGNMMfUX
            uIaw8KB4afGP1Td6uRrrnqyLaEj6K/Rzlvm1RKkkZVLa0kEKl1VwVVUNCmegTmBD
            MJkIwKx8H4Vl8UeZhIca4vuy/lYFzdT+LSQAd0AFVAQfCci7syjpoy4fus0gaRAx
            Q9sl9hV801n5dbnZh+L28qxsLecoyUTYN8JvBFRuIgACrIL0FuhAYyNchJI6pfTE
            n4fF57znrWx8kkSQDMN2v0rx1Gl3x145+o1H4n9DczEkHjy7Qs91MYu7yFCPTXUh
            ahixuuxpRdlGsSZibE8lKSRuqYCDaoHnMlGohW2sVmGyaP3py/DhTOQSKWvFriDy
            h90K7e0wNf4222aQz/l5JryGcPONdJJdSbBsApxgQGmXqrxDUhTBgfUam6jcUlSO
            /rFqgks7lsAp7dBAvSZYwxTTyQ59iSTqHtpMufWVwiUYZHxglc0l9O2Aab1a0A+n
            o2yuxTuBKqkGu2cNZGVYxSYuiG4i6j5dB1jTSAcirsIGlNQTK154UZhIYPvqtn4H
            0wR2BVmeMWkIQr6zUFk5Ql0vaCNgKbOfO5t9Wb0oT1O8UKrZQcQPaOZe+f4IaujU
            E7Qes5vFYjW/b9ucLzAyxdcJf7cvPIzDc7tC4PVZ18OfwB2d/9+T8ixHTKC1QNXS
            XAFQ6+FlYkMi8cDubLFU1Fx/QVNiUrJ9DgRf0kva+MlOqycDclKMAJGQM0xRD/++
            tZPVZDebRJY+twlPezLrS/zR2yYexb9xdKqLbb6gI/Ae8NjZhyLyG7S3v7fG
            =n925
            -----END PGP MESSAGE-----
          fp: 1D680E552A5E0A5FEAAA25797FC30FE4DF65B0D0
        - created_at: "2022-04-01T17:07:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+NYYOrENI4tAQ//WyN1U4MIjLnGk1KX+9CD8hYFoe8oIRutW17ThwXWjJSI
            WH/b2ct3aTGivHRl/mhHK8ebB6jCSDAjY/2DtsMCIEH4aFUQs3nRt/aV/5mxq+oL
            gq0UlwJntw2D5JWndjOxZsQKl8njfgxQkT5EnljmiGxs4+s2l8yqFTephYjqk0C4
            5yggx4HvU9NF1MSruarxwRNZoTMZJcsFagqXokRmI7yBgohtmhMjz3QbWeRiPQE0
            6IZBJ0cWEH2hMrx8Tmz6lxbsXZnic+Wc3xOBHlEdU+9Q0KbytQFO93MPTZsF7Ert
            KPoVNJiF6vCle9ohfjhxFPSxg1kdAYLlY7mFN3ZSjl0hXVfSJFc5Lo/83+ozyyDx
            Kg5hcAPH2JZ/kPZ5JDM37GvrZlC+qMEExYcJAow8ftLWIKvc2T8Ak9xIfvmCKOIU
            D4haex8U4cPRS2kwfkuU4Mk6wOwRGm9IGJ9MqvT74OKJC4mBaGSYQHlrBNdKUq/E
            rTtkPv3mCWrlWiMaGTNOp4tN7p/059fN9m6XG+GzKydfk8RFoqjuG70G6bFn1+FU
            /klWNV0aEvqtC9GkR3asxcnANd5X9dI6yjZuLqJDPRZ55g5PCAA69KXfb0eDGtEY
            7tpZF89XHjIFKR/lxyYDwe2qmUlwn7m1G3DUq9LKuCbeMX7O8E5baan4n23Kr+PS
            XAH78IIvNj5bauiYtDaxZonvLrt7140NXj/Hdvai+Vk5FgMDIBob/U26s2vNZvKV
            pac2sKTMOKxtwGQwgAkrbi5ZxNb4XG8ZkLyTCMmrS8KV+Z7rBba15JniGfds
            =NHys
            -----END PGP MESSAGE-----
          fp: DDEAB23087BC7E8B17DA1F4FD961AC8AAEF425C2
        - created_at: "2022-04-01T17:08:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+cLHljwkAiwAQ//UkNMdLe6ab+vWBAkY90VZwhu2QIZNe2VB7VCgUKgTUvX
            a+1d1odc7MULTtDBOC1iT9bHf7/VeTN1lslRHWKbAboB/LP3jGBdmaqQyRtP3E2x
            3TwARDJWLF6ubZlcWkseZvKPjZTEMHAPGtTbPVUFy0rGFBNWqYtf8liCrIluPjMy
            2zlfg5haAZ0TB5BHGDjG002pbV1cW+SqXt6IRivchVYI1NRQq1Elo3s0wDtPX4hI
            9ZFB0QKZ4HMqNcj0CkDzgBcteJ7ojzTZ2261rjPtHYdXVslDMvWQgrNIN85h5hZP
            +mynQA2tgP6/DD/wXcWS2V7Nh7Kfb/A8MlPmEFiWRYA2ajuXv6PBUoIDAw1x+DE/
            +vgG/1f/K4ZUKzG8hWWFccfIXFDxLWwxrUDRLDi9e0G4mAWqbZw130TTqmeGhwg6
            5rkqeZxPeV7V8Nv0K/hDNrVGkpq/jlGf0YL6gdvWksLX+YRmYGYMAeLcBntt2MKa
            hSbbDFyeLjpupEeM5xWBYgye9gKqTM7qMTKiqO8Mfnm2/yPiQWAX1hM6b44UY2Zm
            8B48YNGRUTCR8qsb6qsDJwBAlpBsxztnRsKq3n9QPCe/Yn9jgRamNJjEZ8dfwLE6
            oL8fPTe35CA7iI+wVnweZTIzQUy+TkMpINE8xmIugiiJeFNdMQvFqXvOyFVzOWLS
            XAEHQG6ayw/p+FStR5ppELng72K2A0IEsxFDl6wNRntgwTtqLjeCflFE0kWGgaVX
            AULwI1WpQn8jf2PLguKDTqAMSudu0R3NP5H6nlMCDhyrGs+5FGQkORrA/mHO
            =vip+
            -----END PGP MESSAGE-----
          fp: C60522A91ED1443D44AB79C093267DD7715CAC18
    unencrypted_regex: ^(implementer|name)$
    version: 3.7.2
